blocks:
  air: 0
  oak_leaves: 1
  spruce_leaves: 2
  birch_leaves: 3
  jungle_leaves: 4
  dark_oak_leaves: 5
  acacia_leaves: 6
  azalea_leaves: 7
  flowering_azalea_leaves: 8
  cherry_leaves: 9
  mangrove_leaves: 10
  oak_log: 11
  spruce_log: 12
  birch_log: 13
  jungle_log: 14
  dark_oak_log: 15
  acacia_log: 16
  tall_grass: 17
  short_grass: 18
  fern: 19
  grass_block: 20
  moss_block: 21
  moss_carpet: 22
  dandelion: 23
  poppy: 24
  blue_orchid: 25
  allium: 26
  azure_bluet: 27
  red_tulip: 28
  white_tulip: 29
  pink_tulip: 30
  oxeye_daisy: 31
  sunflower: 32
  peony: 33
  pink_petals: 34
  brown_mushroom: 35
  red_mushroom: 36
  brown_mushroom_block: 37
  stone: 38
  cobblestone: 39
  mossy_cobblestone: 40
  andesite: 41
  granite: 42
  diorite: 43
  dirt: 44
  coarse_dirt: 45
  snow: 46
  snow_block: 47
  ice: 48
  packed_ice: 49
  cactus: 50
  vine: 51
  lily_pad: 52
  dead_bush: 53
  oak_sapling: 54
  spruce_sapling: 55
  birch_sapling: 56
  jungle_sapling: 57
  dark_oak_sapling: 58
  acacia_sapling: 59
  azalea: 60
  flowering_azalea: 61
